[README fix]
eclipse-bluechi/bluechi pull request #114
Opened 2023-02-07 08:10 UTC by Yarboa

README.developer.md link was broken
Some linting fixes added

2023-02-07 08:53 UTC, mwperina requested changes
Sorry, but converting all links from in-place to end-of-document doesn't make sense, it will just force you to click twice to get where you want

2023-02-07 08:56 UTC, mwperina commented on README.md
> +More infomation about the development can be found in [README.developer](README.developer.md).
Please just fix the link URL to:

```
[README.developer.md](README.developer.md)
```

2023-02-08 11:37 UTC, Yarboa commented on README.md
> +More infomation about the development can be found in [README.developer](README.developer.md).
Sure, 
Just run markdown linter and fixed some
as per this https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/about-writing-and-formatting-on-github

2023-02-08 12:52 UTC, rhatdan commented
LGTM

2023-02-12 12:49 UTC, Yarboa commented
Closing due to this  https://github.com/containers/hirte/pull/136 PR

2023-02-13 07:02 UTC, closed without merging