Run codespell on all PRs and update Makefile to make more user friendly.
eclipse-bluechi/bluechi pull request #134
Opened 2023-02-09 17:48 UTC by rhatdan

2023-02-09 17:51 UTC, mwperina approved these changes
+1

2023-02-09 17:53 UTC, mwperina requested changes
Could you please add `codespell` installation to line 28?

2023-02-10 10:01 UTC, mwperina approved these changes
+1

2023-02-10 10:55 UTC, engelmi approved these changes
LGTM

2023-02-10 10:55 UTC, merged