Default the managerhosts value to 127.0.0.1
eclipse-bluechi/bluechi pull request #247
Opened 2023-04-18 21:10 UTC by rhatdan

2023-04-19 08:24 UTC, mwperina requested changes

2023-04-19 08:24 UTC, mwperina commented on doc/man/hirte-agent.conf.5.md
> +The host used by `hirte-agent` to connect to `hirte`. Must be a valid IPv4 or IPv6. The option defaults to 127.0.0.1, it's mandatory to set this option on remote hirte-agents.
Could you please update the default value also in below files?

https://github.com/containers/hirte/blob/main/config/agent/agent.conf#L14
https://github.com/containers/hirte/blob/main/config/agent/hirte-default.conf#L10
https://github.com/containers/hirte/blob/main/doc/man/hirte-agent.1.md?plain=1#L27

2023-04-19 08:28 UTC, engelmi commented on src/agent/agent.c
> +                value="127.0.0.1";
I think the value of the default host should defined next to the default port in [protocol.h](https://github.com/containers/hirte/blob/main/src/libhirte/common/protocol.h#L6).

2023-04-19 08:28 UTC, engelmi commented on src/agent/agent.c
> +        if (!value) {
The default port is set in the [agent_new()](https://github.com/containers/hirte/blob/main/src/agent/agent.c#L323) and - if I understand it correctly - overridden if it is defined in any of the config options. For consistency, it should be the same for the host.

2023-04-19 10:56 UTC, mwperina approved these changes
+1

2023-04-20 23:29 UTC, rhatdan commented
@engelmi PTAL and merge if it you will.

2023-04-21 14:49 UTC, engelmi approved these changes
LGTM

2023-04-21 14:54 UTC, merged