build: create make rpm and make srpm
eclipse-bluechi/bluechi pull request #285
Opened 2023-05-07 18:13 UTC by dougsland

Make life easier to build packages for devs.
Previously, I had to dig the source code to find
the script.

GH-Issue: https://github.com/containers/hirte/issues/284

Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>

2023-05-08 09:11 UTC, engelmi reviewed
Our primary build system is [meson](mesonbuild.com/) and most targets in the Makefile just delegate to it - so we should keep this file rather slim. However, you are right that the info on how to build the rpm is rather hidden.  

I'd propose to create custom targets to meson, similar to `clang-tidy`:
https://github.com/containers/hirte/blob/main/meson.build#L72C23-L78
There you can also check if `rpmbuild` is installed. Then, change the make targets here to:
```Makefile
rpm: 
   ninja -C {BUILDDIR} build-rpm
```

2023-05-09 08:29 UTC, mwperina commented
> Our primary build system is [meson](mesonbuild.com/) and most targets in the Makefile just delegate to it - so we should keep this file rather slim. However, you are right that the info on how to build the rpm is rather hidden.
> 
> I'd propose to create custom targets to meson, similar to `clang-tidy`: https://github.com/containers/hirte/blob/main/meson.build#L72C23-L78 There you can also check if `rpmbuild` is installed. Then, change the make targets here to:
> 
> ```makefile
> rpm: 
>    ninja -C {BUILDDIR} build-rpm
> ```

I think current patch is OK, because meson is executed as a part of build scripts. I don't see a reason why we should call those scripts from meson itself, it would be a bit chicken egg problem

2023-05-09 08:29 UTC, mwperina approved these changes
+1

2023-05-09 12:16 UTC, dougsland commented
@engelmi @mwperina Thanks for the comments. I was thinking like: "makefile triggers the real build system (whatever it is)" which in this case is `meson` and generates the `srpm` and `rpm` files. Is that correct?

2023-05-09 12:51 UTC, mwperina commented
> @engelmi @mwperina Thanks for the comments. I was thinking like: "makefile triggers the real build system (whatever it is)" which in this case is `meson` and generates the `srpm` and `rpm` files. Is that correct?

So build system is meson, Makefile is just a facade to meson for users, which are not familiar with meson.

But RPM build is standalone, because meson is execute within the RPM build process, that's why we have those build scripts.

So as Makefile is only a facade, I think it's OK that we are calling RPM build scripts from Makefile

2023-05-09 14:11 UTC, engelmi commented
> @engelmi @mwperina Thanks for the comments. I was thinking like: "makefile triggers the real build system (whatever it is)" which in this case is `meson` and generates the `srpm` and `rpm` files. Is that correct?
>

Yes, you are correct. 
 
> So build system is meson, Makefile is just a facade to meson for users, which are not familiar with meson.
> 
> But RPM build is standalone, because meson is execute within the RPM build process, that's why we have those build scripts.
> 
> So as Makefile is only a facade, I think it's OK that we are calling RPM build scripts from Makefile

Yes, the RPM builds are standalone, but its still a bit inconsistent if we call it directly from the Makefile - since it is only a facade for meson, but bypasses it for the RPM build. Not a big issue, I think, so both approaches are fine with me.

2023-05-09 17:49 UTC, dougsland commented
> > @engelmi @mwperina Thanks for the comments. I was thinking like: "makefile triggers the real build system (whatever it is)" which in this case is `meson` and generates the `srpm` and `rpm` files. Is that correct?
> 
> Yes, you are correct.
> 
> > So build system is meson, Makefile is just a facade to meson for users, which are not familiar with meson.
> > But RPM build is standalone, because meson is execute within the RPM build process, that's why we have those build scripts.
> > So as Makefile is only a facade, I think it's OK that we are calling RPM build scripts from Makefile
> 
> Yes, the RPM builds are standalone, but its still a bit inconsistent if we call it directly from the Makefile - since it is only a facade for meson, but bypasses it for the RPM build. Not a big issue, I think, so both approaches are fine with me.

Great, so let's move with what we have now which ready to go/merge. :)

2023-05-10 08:34 UTC, pypingou commented on Makefile
> +	@build-scripts/build-rpm.sh
Does this really build a srpm? It seems to be doing the same thing as `make rpm`

2023-05-10 10:04 UTC, mwperina commented on Makefile
> +	@build-scripts/build-rpm.sh
Good catch, I missed that :-(

2023-05-10 10:05 UTC, mwperina requested changes
Please check .src.rpm is built properly using `make srpm`

2023-05-12 14:22 UTC, dougsland commented on Makefile
> +	@build-scripts/build-rpm.sh
pingou++ mperina++ me-- ;-)

2023-05-12 14:22 UTC, dougsland commented
@mwperina @engelmi @pypingou please re-review. Thanks!

2023-05-14 11:19 UTC, rhatdan commented
LGTM

2023-05-15 06:36 UTC, engelmi approved these changes
LGTM

2023-05-15 06:57 UTC, mwperina approved these changes
+1

2023-05-15 06:57 UTC, merged