Add agent heartbeat timestamps to client node monitoring.
eclipse-bluechi/bluechi pull request #338
Opened 2023-06-04 17:01 UTC by sdunnagan

This addresses issue #337, adding the last heartbeat timestamp in client node monitoring.

```
NODE                          |     STATE|      LAST HEARTBEAT|
===============================================================
agent-001                     |    online|     Jun 04 12:28:03|
agent-002                     |   offline|                    |
```

If the node goes offline, you can determine from the last heartbeat timestamp when it went down.

2023-06-05 10:38 UTC, pypingou commented
Should we add a test for this somewhere?

2023-06-05 12:08 UTC, sdunnagan commented
Yep!  I suggest I add an integration test in a follow-up PR.

2023-06-06 10:05 UTC, pypingou commented
On Mon, Jun 05, 2023 at 05:08:48AM -0700, Steve Dunnagan wrote:
> Yep!  I suggest I add an integration test in a follow-up PR.

Why splitting this into two PR? Due to time availability or is there another
reason?

2023-06-06 12:06 UTC, engelmi requested changes
Overall looks good! 
I have a few minor comments, and a bigger change request to move the timestamp creation to the manager side and only updating the timestamp field of the node.

2023-06-06 12:06 UTC, engelmi commented on data/org.containers.hirte.internal.Agent.xml
> +      <arg name="nodeName" type="s" />
`arg`s should be snake_case, so `node_name` in this case. It is also wrong in other locations in `data/` (e.g. the `unitName` above). Would be great if you could check and change these as well :) 
*Note:* the fields are also in the `vtable`s in C code

2023-06-06 12:06 UTC, engelmi commented on src/libhirte/common/protocol.h
> -#define AGENT_HEARTBEAT_SIGNAL_NAME "Heartbeat"
I think you can re-add the signal name here and use it when emitting and matching it. In that aspect it is cleaner than the other signals we have (there is already issue #109 to do this for all the others as well).

2023-06-06 12:06 UTC, engelmi commented on src/manager/node.c
> +        strncpy(node->heartbeat_timestamp, timestamp, AGENT_HEARTBEAT_TIMESTAMP_SIZE - 1);
You can use the [copy_str](https://github.com/containers/hirte/blob/main/src/libhirte/common/string-util.h#L38-L46) from libhirte instead and check with `== NULL` for an error.

2023-06-06 12:06 UTC, engelmi commented on src/manager/node.c
> +        manager_node_connection_state_update(node->manager, node->name, "online", node->heartbeat_timestamp);
`manager_node_connection_state_update` will emit the `NodeConnectionState`. Calling it here will result in continuously emitting (a lot of) signals all the time due to the heartbeat - even if no monitor is watching those changes. 
To avoid this unnecessary traffic, it is better to extend the monitor functionality in hirte - e.g. making it possible to subscribe to the node connections. But thats a bigger change, I think, so it would be fine to just remove this `manager_node_connection_state_update` here and use the timestamp we collect with the `ListUnits` in hirtectl for now.

2023-06-06 12:06 UTC, engelmi commented on src/agent/agent.c
> +                time_t t = time(NULL);
It would be better to get the timestamp in the `node_match_heartbeat` function on the manger side. This way, the agent doesn't need to be changed and, more importantly, we have a "unified" timestamp. For example, each node (incl. the node the manager is running on) could have a different time. Using the timestamp on the manager also enables us to confidently calculate a duration, e.g. node has been offline since 1 hour. 
Therefore, getting the timestamp in `node_match_heartbeat` seems like a better option.

2023-06-06 12:06 UTC, engelmi commented on src/manager/manager.c
> +        int r = sd_bus_message_open_container(reply, SD_BUS_TYPE_STRUCT, "soss");
This requires an update in 
- https://github.com/containers/hirte/blob/main/data/org.containers.hirte.Manager.xml#L8-L10
- https://github.com/containers/hirte/blob/main/doc/docs/api/description.md (for the `org.containers.hirte.Manager interface and ListNodes method)

2023-06-06 12:14 UTC, engelmi commented
> On Mon, Jun 05, 2023 at 05:08:48AM -0700, Steve Dunnagan wrote: Yep! I suggest I add an integration test in a follow-up PR.
> Why splitting this into two PR? Due to time availability or is there another reason?

The monitoring in `hirtectl` can't really be tested, I think (but maybe I am missing something). So we'd have to use the D-Bus API, create a monitor + subscription with custom node-connection handling to reliably test this - which is a bit more effort. Is it ok to create a gh issue (and add it to the integration test epic in jira) to keep track of it? @pypingou 
P.S.: This is probably one of the use cases for the Python SDK @dougsland was talking about :)

2023-06-06 13:23 UTC, sdunnagan commented on src/manager/node.c
> +        manager_node_connection_state_update(node->manager, node->name, "online", node->heartbeat_timestamp);
Without emitting `NodeConnectionState` when the heartbeat arrives, the node monitoring would no longer be "LAST HEARTBEAT", and instead something like "NODE UP/DOWN".  I like being able to see when the heartbeat went down.

If we don't want so much D-Bus traffic from signals, we could slow down the heartbeat signals from the agents.

We could even eventually take other actions based on when the agent went down, aside from just monitoring node status with `hirtectl`.  It's seem important for the manager to know when the agent went down.

2023-06-06 14:27 UTC, sdunnagan commented on src/manager/node.c
> +        manager_node_connection_state_update(node->manager, node->name, "online", node->heartbeat_timestamp);
I like your suggestion of changing "LAST HEARTBEAT" to "LAST SEEN".  I'll update the PR accordingly.

2023-06-06 14:36 UTC, sdunnagan commented on src/agent/agent.c
> +                time_t t = time(NULL);
I don't follow why not have the agent calculate the heartbeat timestamp.  The manager can calculate how long the agent has been offline by comparing its current time with the Node's new `heartbeat_timestamp` attribute.

2023-06-06 14:49 UTC, sdunnagan commented on src/agent/agent.c
> +                time_t t = time(NULL);
I see your point.  We've changed the meaning of the heartbeat from "LAST HEARTBEAT" to "LAST SEEN".  Now the timestamp is from the manager's perspective.

2023-06-06 15:41 UTC, sdunnagan commented
We decided not to add timestamps to the agent heartbeat signals.

2023-06-06 15:41 UTC, closed without merging