Documintation for SetLogLevel
eclipse-bluechi/bluechi pull request #376
Opened 2023-07-02 05:09 UTC by ArtiomDivak

Wrote some documintation of how and where setloglevel is implemanted.

2023-07-02 17:31 UTC, dougsland reviewed
the PR title has a typo: 

:s/Documintation/Documentation/g

Other than that looks good to me.

2023-07-02 17:31 UTC, dougsland commented on doc/docs/api/description.md
> +    Set log level for hirte-agent by invoking the internal hirte agebt API.
typo: :s/agebt/agent/g

2023-07-03 07:54 UTC, engelmi commented on doc/docs/api/description.md
> +  * `SetLogLevel()`
```suggestion
  * `SetLogLevel(in s log_level)`
```
Doesn't it require the log level as input parameter?

2023-07-03 07:54 UTC, engelmi commented on doc/docs/api/description.md
> +  * `SetLogLevel(in s loglevel)`
```suggestion
  * `SetLogLevel(in s log_level)`
```
I think for the parameters we use `snake_case`. Could you please change that for the others as well? (I know we are not 100% consistent here - so if you want to change the other `camelCases` to `snake_case` that would be awesome :))

2023-07-03 07:54 UTC, engelmi commented on doc/docs/api/description.md
> +    Set new log level for hirte manager.
Could you mention that this change is not being persisted and is only effective as long as hirte/-agent is not restarted?

2023-07-07 13:27 UTC, mwperina commented on doc/docs/api/description.md
> +    Set new log level for hirte manager. This change is persistent as long as hirte not restarted.
I'd change to `Set the new log level ...`.
And also shouldn't we use the word *controller* instead of *manager*?

2023-07-07 13:29 UTC, mwperina reviewed
Please also fix typos in commit subject and message

2023-07-10 08:28 UTC, mwperina commented
Could you please split commits for unrelated changes? Right now I see 2 commits:

1. Changes around set log level
2. Changes around parameter names

And please don't forget about typos in commit's subject and message

2023-07-10 13:36 UTC, mwperina commented
Please perform the correct rebase on top of latest change. Other than that it looks good to me.

2023-07-11 07:11 UTC, mwperina requested changes

2023-07-11 07:11 UTC, mwperina commented on doc/docs/api/description.md
> +    Set the new log level for hirte-agent node. This change is persistent as long as hirte-agrnt not restarted.
hirte-agrnt -> hirte-agent

2023-07-12 06:25 UTC, engelmi approved these changes
LGTM

2023-07-12 07:31 UTC, mwperina approved these changes
+1

2023-07-12 07:31 UTC, merged