doc/examples: golang - list_nodes.go
eclipse-bluechi/bluechi pull request #522
Opened 2023-08-31 21:21 UTC by dougsland

Just an example how to use golang and bluechi.

Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>

2023-08-31 21:29 UTC, dougsland commented
I was just looking for test bluechi + golang and this should be enough until we have a dbus generation to a golang module as we have in python.

2023-09-01 07:10 UTC, engelmi requested changes
I really like adding more languages to the list of examples on how to use the D-Bus API :) I have a few change requests, though.

2023-09-01 07:10 UTC, engelmi commented on doc/bluechi-examples/golang/.gitignore
> +list_nodes
The `.gitignore` here is not needed. Could you please remove it?

2023-09-01 07:10 UTC, engelmi commented on doc/bluechi-examples/golang/README.md
> +# golang examples
The content of this file should be appended to https://github.com/containers/bluechi/blob/main/doc/docs/api/examples.md as a new section
```
## GoLang

...
```

2023-09-01 07:10 UTC, engelmi commented on doc/bluechi-examples/golang/list_nodes.go
> +// SPDX-License-Identifier: LGPL-2.1-or-later
The `doc/bluechi-examples` is intended for the bindings (only python currently) - maybe the directory name is misleading. Could you please move it to `doc/api-examples/go/list_nodes.go`?

2023-09-01 07:10 UTC, engelmi commented on doc/bluechi-examples/golang/README.md
> +
Could you add another section here for showing the content of `list_nodes.go`? Then you can integrate the source file like this
```go
--8<-- "api-examples/go/list_nodes.go"
```

Maybe we need to add a new package to the readthedocs, but we can do that after this PR is merged.

2023-09-01 14:25 UTC, dougsland commented
closing, rebase made a mess.

2023-09-01 14:25 UTC, closed without merging

2023-09-01 14:42 UTC, dougsland commented
the new one: https://github.com/containers/bluechi/pull/528