Save .gcno files after meson build
eclipse-bluechi/bluechi pull request #574
Opened 2023-09-20 09:07 UTC by ArtiomDivak

.gcno files are needed to get full coverage.
This PR will save those files in a ${datadir}/coverage so we can use
them later on to get the coverage with .gcna files.

Fixes:https://github.com/containers/bluechi/issues/397
Signed-off-by: Artiom Divak <adivak@redhat.com>

2023-09-20 09:20 UTC, mwperina requested changes

2023-09-20 09:20 UTC, mwperina commented on copyGcno.sh
Please move this script to `build-scripts` directory and probably rename to something like `install-coverage.sh`.

2023-09-20 09:20 UTC, mwperina commented on copyGcno.sh
> +#!/bin/sh
Please align the header with other shell files we have in `build-scripts` directory

2023-09-20 09:20 UTC, mwperina commented on copyGcno.sh
> +
It seems too complex, I suggest you:

1. Use existing `MESON*` environment variables that meson exposes during install script execution, you can display them by running `set > /tmp/meson-env.txt` and checking the file
2. You could you single line combination of find and cp commands

2023-09-20 09:20 UTC, mwperina commented on meson.build
> +meson.add_install_script('copyGcno.sh', './src', join_paths(get_option('prefix'), get_option('datadir'), 'cover'))
We need to use that install script only when `with_coverage` is enabled

2023-09-20 11:57 UTC, mwperina commented on build-scripts/install-coverage.sh
> +done
It's still too complex, what about something like this?

```
+#!/bin/bash -xe
+# SPDX-License-Identifier: LGPL-2.1-or-later
+
+# This script should be executed only from meson as a part of install flow!
+#
+# Install all created `*.gcno` files so they could be packaged into bluechi-coverage RPM.
+COV_DIR="${MESON_INSTALL_DESTDIR_PREFIX}/share/bluechi-coverage"
+mkdir -p "${COV_DIR}"
+find "${MESON_BUILD_ROOT}" -name '*.gcno' -exec cp "{}" "${COV_DIR}" \;
```

2023-09-20 12:00 UTC, mwperina commented on meson.build
> +   meson.add_install_script('./build-scripts/install-coverage.sh')
Please add a comment so it's known why we needed to use custom install script:

```
# Coverage source code mapping files `*.gcno` are created as a part of the build for each `*.c` file, but it's
# very hard to tell meson to install files, which are created as a side effect from the build, so it's easier
# to use custom install script
meson.add_install_script('build-scripts/install-coverage.sh')
```

2023-09-20 13:01 UTC, mwperina requested changes

2023-09-20 13:01 UTC, mwperina commented on build-scripts/install-coverage.sh
> +#!/bin/sh -xe
Please align with existing scripts:

```
#!/bin/bash -xe
```

2023-09-20 13:01 UTC, mwperina commented on test.sh
This file should not be part of the commit

2023-09-21 17:50 UTC, dougsland commented
seems sane to me. LGTM.

2023-09-21 17:58 UTC, mwperina commented
> seems sane to me. LGTM.

Not finished yet, spec file part needs to be added before merging

2023-09-27 12:47 UTC, mwperina approved these changes
LGTM

2023-09-27 12:48 UTC, merged