Add bluechi_is_online node module and integration test
eclipse-bluechi/bluechi pull request #999
Opened 2024-12-04 11:40 UTC by nsimsolo

Adding test for bluechi-is-online node.
'bluechi-is-online node' command is verifying on the controller machine (check and/or monitor) the connection of the given node to the controller
When the node is online, it exits with a status code 0 and does not produce any CLI output.

Fixes: https://github.com/eclipse-bluechi/bluechi/issues/982
Signed-off-by: Nisim Simsolo [nsimsolo@redhat.com](mailto:nsimsolo@redhat.com)

2024-12-04 12:02 UTC, mwperina requested changes
Can't we put the whole `.idea` directory into `.gitignore` file?

2024-12-04 12:02 UTC, mwperina commented on tests/tests/tier0/bluechi-is-online-node/test_bluechi_is_online_node.py
> +    assert result, f"bluechi controller for node {node_name} should be online"
The message should be: "bluechi-agent for node {node_name} should be online"

2024-12-04 12:02 UTC, mwperina commented on tests/tests/tier0/bluechi-is-online-node/test_bluechi_is_online_node.py
> +    assert ctrl.wait_for_unit_state_to_be("bluechi-controller", "inactive")
You should stop the bluechi-agent on node-foo and not the controller itself

2024-12-04 12:02 UTC, mwperina commented on tests/tests/tier0/bluechi-is-online-node/test_bluechi_is_online_node.py
> +    assert not result, f"Bluechi controller for node {node_name} should be offline"
The message should be "bluechi-agent for node {node_name} should be offline"

2024-12-04 12:40 UTC, engelmi commented
> Can't we put the whole `.idea` directory into `.gitignore` file?

Yes, the `.idea` and `inspectionProfiles` directories are IDE specific and shouldn't be added to the repo. Please remove them from the commit and - optionally - add two entries to `.gitignore`.

2024-12-04 14:16 UTC, nsimsolo commented on tests/tests/tier0/bluechi-is-online-node/test_bluechi_is_online_node.py
> +    assert result, f"bluechi controller for node {node_name} should be online"
Fixed

2024-12-04 14:17 UTC, nsimsolo commented on tests/tests/tier0/bluechi-is-online-node/test_bluechi_is_online_node.py
> +    assert ctrl.wait_for_unit_state_to_be("bluechi-controller", "inactive")
Done

2024-12-04 14:17 UTC, nsimsolo commented on tests/tests/tier0/bluechi-is-online-node/test_bluechi_is_online_node.py
> +    assert not result, f"Bluechi controller for node {node_name} should be offline"
Fixed

2024-12-04 14:32 UTC, mwperina requested changes
Test looks good, but please remove this `.idea` directory from the commit

2024-12-05 07:53 UTC, mkemel commented
/packit retest-failed

2024-12-05 07:53 UTC, mkemel commented
/packit build

2024-12-05 09:00 UTC, mwperina approved these changes
LGTM

2024-12-05 09:01 UTC, mkemel approved these changes
LGTM

2024-12-05 09:03 UTC, engelmi approved these changes
LGTM

2024-12-05 13:52 UTC, merged